#ifndef _SYSCFG_COMMON_H_
#define _SYSCFG_COMMON_H_

#include "typedef.h"
#include "memorymap.h"

#define SYSCFG_OFFSET    (0x00003800)
#define SYSCFG           GET_ADDR(PERIPHERAL_APB2_BASE + SYSCFG_OFFSET)

// SYSCFG_EXTICR1 ~ SYSCFG_EXTICR14 (0x08 ~ 0x14)
#define SYSCFG_EXTICR1_OFFSET          0x08
#define SYSCFG_EXTICR2_OFFSET          0x0C
#define SYSCFG_EXTICR3_OFFSET          0x10
#define SYSCFG_EXTICR4_OFFSET          0x14

#define READ_SYSCFG_EXTICRx(EXTICRx)                READ_REG_LWORD(SYSCFG, SYSCFG_EXTICR1_OFFSET + (EXTICRx)*4)
#define WRITE_SYSCFG_EXTICRx(EXTICRx, u32Value)     WRITE_REG_LWORD(SYSCFG, SYSCFG_EXTICR1_OFFSET + (EXTICRx)*4, (u32Value))

typedef enum {
    EXTI_GPIOA,
    EXTI_GPIOB,
    EXTI_GPIOC,
    EXTI_GPIOD,
    EXTI_GPIOE,
    EXTI_GPIOF,
    EXTI_GPIOG,
    EXTI_GPIOH,
    EXTI_GPIOX_END
} EXTI_GPIOX;

static const BYTE EXTI_GPIOX_TABLE[EXTI_GPIOX_END] = {
    [EXTI_GPIOA] = 0,
    [EXTI_GPIOB] = 1,
    [EXTI_GPIOC] = 2,
    [EXTI_GPIOD] = 3,
    [EXTI_GPIOE] = 4,
    [EXTI_GPIOF] = 5,
    [EXTI_GPIOG] = 6,
    [EXTI_GPIOH] = 7
};

// EXTI0 ~ EXTI3
#define READ_SYSCFG_EXTICR1()                       READ_SYSCFG_EXTICRx(0)
#define WRITE_SYSCFG_EXTICR1(u32Value)              WRITE_SYSCFG_EXTICRx(0, u32Value)
#define CLEAR_SYSCFG_EXTICR1_EXTIx(EXTIx)           WRITE_SYSCFG_EXTICR1(READ_SYSCFG_EXTICR1() & (~(0xF << ((EXTIx % 4) * 4))))
#define SET_SYSCFG_EXTICR1_EXTIx(EXTIx, EXTI_GPIOx) WRITE_SYSCFG_EXTICR1(READ_SYSCFG_EXTICR1() | (EXTI_GPIOX_TABLE[EXTI_GPIOx] << ((EXTIx % 4) * 4)))

// EXTI4 ~ EXTI7
#define READ_SYSCFG_EXTICR2()                       READ_SYSCFG_EXTICRx(1)
#define WRITE_SYSCFG_EXTICR2(u32Value)              WRITE_SYSCFG_EXTICRx(1, u32Value)
#define CLEAR_SYSCFG_EXTICR2_EXTIx(EXTIx)           WRITE_SYSCFG_EXTICR2(READ_SYSCFG_EXTICR2() & (~(0xF << ((EXTIx % 4) * 4))))
#define SET_SYSCFG_EXTICR2_EXTIx(EXTIx, EXTI_GPIOx) WRITE_SYSCFG_EXTICR2(READ_SYSCFG_EXTICR2() | (EXTI_GPIOX_TABLE[EXTI_GPIOx] << ((EXTIx % 4) * 4)))

// EXTI8 ~ EXTI11
#define READ_SYSCFG_EXTICR3()                       READ_SYSCFG_EXTICRx(2)
#define WRITE_SYSCFG_EXTICR3(u32Value)              WRITE_SYSCFG_EXTICRx(2, u32Value)
#define CLEAR_SYSCFG_EXTICR3_EXTIx(EXTIx)           WRITE_SYSCFG_EXTICR3(READ_SYSCFG_EXTICR3() & (~(0xF << ((EXTIx % 4) * 4))))
#define SET_SYSCFG_EXTICR3_EXTIx(EXTIx, EXTI_GPIOx) WRITE_SYSCFG_EXTICR3(READ_SYSCFG_EXTICR3() | (EXTI_GPIOX_TABLE[EXTI_GPIOx] << ((EXTIx % 4) * 4)))

// EXTI12 ~ EXTI15
#define READ_SYSCFG_EXTICR4()                       READ_SYSCFG_EXTICRx(3)
#define WRITE_SYSCFG_EXTICR4(u32Value)              WRITE_SYSCFG_EXTICRx(3, u32Value)
#define CLEAR_SYSCFG_EXTICR4_EXTIx(EXTIx)           WRITE_SYSCFG_EXTICR4(READ_SYSCFG_EXTICR4() & (~(0xF << ((EXTIx % 4) * 4))))
#define SET_SYSCFG_EXTICR4_EXTIx(EXTIx, EXTI_GPIOx) WRITE_SYSCFG_EXTICR4(READ_SYSCFG_EXTICR4() | (EXTI_GPIOX_TABLE[EXTI_GPIOx] << ((EXTIx % 4) * 4)))

#endif